trial_structure:
 Nrealisations: 1000
 Ntrials: 40

ground_truth:
  prob_at_thresh: 0.5
  thresh_srt: 0
  slope_at_thresh: 0.1
  prob_miss: 0.01
  prob_guess: 0
  func_type: 1

model_parameters:
 srt_percentage: 0.5
 miss_rate: 0.01
 guess_rate: 0
 min_snr: -20
 max_snr: 20
 min_slope: 0
 max_slope: 0.5

basie_parameters: # [default]
 nx: 40 # number of SNR values in pdf [40]
 ns: 21 # number of slope values in pdf [21]
 nh: 30 # number of probe SNR values to evaluate [30]
 cs: 1 # weighting of slope relative to SRT in cost function [1]
 dh: 0.2 # minimum step size in dB for probe SNRs [0.2]
 sl: 0.005 # min slope at threshold (must be >0) [0.005]
 kp: 4 # number of std deviations of the pdfs to keep [4]
 hg: 1.3 # amount to grow expected gains in ni trials [1.3]
 cf: 2 # cost function: 1: variance, 2: v_entropy [2]
 pm: 1 # psychometric model: 1: logistic, 2: cumulative gaussian [1]
 lg: 1 # use log slope in pdf: 0: no, 1: yes [1]
 pp: 1 # Number of prior standard deviations in initial semi-range [1]
 pf: 0.0001 # Probability floor (integrated over entire grid) [0.0001]
 ts: 2 # Number of std devs to explore [2]
 dp: 10 # Maximum probe SNR shift (dB) [10]
 it: 0.5 # Grid interpolation threshold [0.5]
 at: 0.1 # Axis change threshold [0.1]
 la: 1 # Look 2-ahead when choosing probe [1]
 op: 0.01 # Outlier probability [0.01]
 rx: 0.5 # Minimum range factor per iteration [0.5]